version: "3"

services:
  database_Service:
    image: postgres:13-alpine
    restart: on-failure
    env_file: .env
    container_name: database_Service
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=photosDb
    ports:
      - "5430:5430"
    volumes:
       - pgdata:/var/lib/postgresql/data
  


  redis_service:
    image: redis:6-alpine
    env_file: .env
    container_name: redis_service_dev
    restart: on-failure
    ports:
      - "6379:6379"

  worker_service_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # image: banking_dev_v1
    container_name: worker_service_dev
    restart: on-failure
    entrypoint: ["./entrypoint_worker.sh"]
    command: ["npm", "run", "start:worker"]
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:secret@database_Service:5430/photosDb?schema=public
      - REDIS_URL=redis://redis_service_dev:6379/
    depends_on:
      - database_Service
      - redis_service
  
  
  api_service:
    depends_on:
      - database_Service
    build: 
       context: .
       dockerfile: Dockerfile.dev
    restart: on-failure
    env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@database_Service:5430/photosDb?schema=public
    stdin_open: true
    tty: true
    command: ["npm", "run","start"]
    entrypoint: ["./entrypoint_dev.sh"]

  frontend:
    build:
      context: ./Photos-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - api_service
    
volumes:
  pgdata:


  
